import type { Asset, AssetClass } from "./types";

/**
 * The tradeable universe. The first nine are the MVP's featured markets and
 * render on the Markets grid in this order; the rest exist so global search
 * and the watchlist have somewhere to grow.
 */
export const ASSETS: Asset[] = [
  {
    symbol: "XAUUSD",
    name: "Gold",
    ticker: "GOLD",
    assetClass: "commodity",
    currency: "USD",
    precision: 2,
    description: "Spot gold priced in US dollars per troy ounce.",
    drivers: [
      "real yields",
      "US dollar strength",
      "central bank buying",
      "safe-haven demand",
    ],
  },
  {
    symbol: "BTCUSD",
    name: "Bitcoin",
    ticker: "BTC",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "Bitcoin priced against the US dollar.",
    drivers: [
      "ETF flows",
      "global liquidity",
      "risk appetite",
      "halving supply dynamics",
    ],
  },
  {
    symbol: "ETHUSD",
    name: "Ethereum",
    ticker: "ETH",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "Ether priced against the US dollar.",
    drivers: [
      "network activity",
      "staking flows",
      "layer-2 adoption",
      "correlation to Bitcoin",
    ],
  },
  {
    symbol: "EURUSD",
    name: "Euro / US Dollar",
    ticker: "EUR/USD",
    assetClass: "forex",
    currency: "USD",
    precision: 5,
    description: "The world's most traded currency pair.",
    drivers: [
      "ECB vs Fed rate differentials",
      "eurozone growth data",
      "energy prices",
    ],
  },
  {
    symbol: "GBPUSD",
    name: "British Pound / US Dollar",
    ticker: "GBP/USD",
    assetClass: "forex",
    currency: "USD",
    precision: 5,
    description: "Sterling against the US dollar, known as cable.",
    drivers: ["Bank of England policy", "UK inflation prints", "risk sentiment"],
  },
  {
    symbol: "USDJPY",
    name: "US Dollar / Japanese Yen",
    ticker: "USD/JPY",
    assetClass: "forex",
    currency: "JPY",
    precision: 3,
    description: "The dollar against the yen — a classic rate-differential pair.",
    drivers: [
      "US Treasury yields",
      "Bank of Japan policy",
      "carry trade positioning",
      "intervention risk",
    ],
  },
  {
    symbol: "NDX",
    name: "NASDAQ 100",
    ticker: "NASDAQ",
    assetClass: "index",
    currency: "USD",
    precision: 2,
    description: "The 100 largest non-financial companies on the NASDAQ.",
    drivers: [
      "megacap earnings",
      "AI capex expectations",
      "long-duration rate sensitivity",
    ],
  },
  {
    symbol: "SPX",
    name: "S&P 500",
    ticker: "S&P 500",
    assetClass: "index",
    currency: "USD",
    precision: 2,
    description: "The benchmark index of US large-cap equities.",
    drivers: ["earnings breadth", "Fed policy path", "credit conditions"],
  },
  {
    symbol: "WTIUSD",
    name: "Crude Oil (WTI)",
    ticker: "OIL",
    assetClass: "energy",
    currency: "USD",
    precision: 2,
    description: "West Texas Intermediate crude oil, per barrel.",
    drivers: [
      "OPEC+ supply policy",
      "inventory builds",
      "geopolitical risk premium",
      "Chinese demand",
    ],
  },

  // --- Extended universe (search + watchlist) ---
  {
    symbol: "XAGUSD",
    name: "Silver",
    ticker: "SILVER",
    assetClass: "commodity",
    currency: "USD",
    precision: 3,
    description: "Spot silver in US dollars per troy ounce.",
    drivers: ["industrial demand", "gold ratio", "solar manufacturing"],
  },
  {
    symbol: "SOLUSD",
    name: "Solana",
    ticker: "SOL",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "Solana priced against the US dollar.",
    drivers: ["network throughput", "DeFi activity", "crypto beta"],
  },
  {
    symbol: "DXY",
    name: "US Dollar Index",
    ticker: "DXY",
    assetClass: "index",
    currency: "USD",
    precision: 3,
    description: "The dollar measured against a basket of major currencies.",
    drivers: ["Fed policy", "global growth spreads", "haven flows"],
  },
  {
    symbol: "AUDUSD",
    name: "Australian Dollar / US Dollar",
    ticker: "AUD/USD",
    assetClass: "forex",
    currency: "USD",
    precision: 5,
    description: "The Aussie dollar, a common proxy for global growth.",
    drivers: ["iron ore prices", "China data", "RBA policy"],
  },
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    ticker: "AAPL",
    assetClass: "stock",
    currency: "USD",
    precision: 2,
    description: "Apple Inc. common stock, listed on NASDAQ.",
    drivers: ["iPhone cycle", "services margin", "China exposure"],
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    ticker: "NVDA",
    assetClass: "stock",
    currency: "USD",
    precision: 2,
    description: "NVIDIA common stock, the bellwether for AI hardware demand.",
    drivers: ["data-centre orders", "export controls", "hyperscaler capex"],
  },
  {
    symbol: "TSLA",
    name: "Tesla, Inc.",
    ticker: "TSLA",
    assetClass: "stock",
    currency: "USD",
    precision: 2,
    description: "Tesla common stock.",
    drivers: ["delivery numbers", "margin per vehicle", "autonomy narrative"],
  },

  // --- Crypto — expanded universe ---
  // Sourced live via CoinGecko (keyless). Deliberately excludes stablecoins —
  // an asset pinned to $1 has no trend to analyse — and thin or obscure
  // tokens that would clutter search without being genuinely followed.
  {
    symbol: "BNBUSD",
    name: "BNB",
    ticker: "BNB",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "BNB, the exchange token for the Binance ecosystem, priced against the US dollar.",
    drivers: ["Binance exchange volume", "token burn schedule", "BNB Chain activity", "exchange-token regulatory risk"],
  },
  {
    symbol: "XRPUSD",
    name: "XRP",
    ticker: "XRP",
    assetClass: "crypto",
    currency: "USD",
    precision: 3,
    description: "XRP, issued by Ripple for cross-border payment settlement, priced against the US dollar.",
    drivers: ["Ripple litigation outcomes", "cross-border payment adoption", "exchange listings"],
  },
  {
    symbol: "TRXUSD",
    name: "TRON",
    ticker: "TRX",
    assetClass: "crypto",
    currency: "USD",
    precision: 4,
    description: "TRON's native token, priced against the US dollar.",
    drivers: ["stablecoin settlement volume", "network fee revenue", "founder-related headline risk"],
  },
  {
    symbol: "DOGEUSD",
    name: "Dogecoin",
    ticker: "DOGE",
    assetClass: "crypto",
    currency: "USD",
    precision: 5,
    description: "Dogecoin, the largest meme coin by market capitalisation, priced against the US dollar.",
    drivers: ["social-media sentiment", "retail speculative flow", "broader crypto beta"],
  },
  {
    symbol: "ZECUSD",
    name: "Zcash",
    ticker: "ZEC",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "Zcash, a privacy-focused cryptocurrency with optional shielded transactions, priced against the US dollar.",
    drivers: ["privacy-coin regulatory scrutiny", "shielded-pool usage", "crypto beta"],
  },
  {
    symbol: "XMRUSD",
    name: "Monero",
    ticker: "XMR",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "Monero, a privacy-focused cryptocurrency with mandatory transaction shielding, priced against the US dollar.",
    drivers: ["exchange delistings", "privacy-coin regulatory scrutiny", "darknet-market demand"],
  },
  {
    symbol: "ADAUSD",
    name: "Cardano",
    ticker: "ADA",
    assetClass: "crypto",
    currency: "USD",
    precision: 4,
    description: "Cardano's native token, priced against the US dollar.",
    drivers: ["protocol upgrade roadmap", "staking participation", "developer activity"],
  },
  {
    symbol: "LINKUSD",
    name: "Chainlink",
    ticker: "LINK",
    assetClass: "crypto",
    currency: "USD",
    precision: 3,
    description: "Chainlink, the oracle network token connecting smart contracts to real-world data, priced against the US dollar.",
    drivers: ["oracle network adoption", "DeFi total value locked", "staking flows"],
  },
  {
    symbol: "XLMUSD",
    name: "Stellar",
    ticker: "XLM",
    assetClass: "crypto",
    currency: "USD",
    precision: 4,
    description: "Stellar's native token, built for cross-border payment rails, priced against the US dollar.",
    drivers: ["payment-corridor partnerships", "network usage", "crypto beta"],
  },
  {
    symbol: "BCHUSD",
    name: "Bitcoin Cash",
    ticker: "BCH",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "Bitcoin Cash, a fork of Bitcoin optimised for lower transaction fees, priced against the US dollar.",
    drivers: ["Bitcoin correlation", "merchant adoption", "block-size debate legacy"],
  },
  {
    symbol: "LTCUSD",
    name: "Litecoin",
    ticker: "LTC",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "Litecoin, one of the earliest Bitcoin forks, priced against the US dollar.",
    drivers: ["Bitcoin correlation", "halving cycle", "payment-processor adoption"],
  },
  {
    symbol: "HBARUSD",
    name: "Hedera",
    ticker: "HBAR",
    assetClass: "crypto",
    currency: "USD",
    precision: 5,
    description: "Hedera's native token, used to pay fees on its enterprise-oriented distributed ledger, priced against the US dollar.",
    drivers: ["enterprise partnership announcements", "network throughput", "council-governance decisions"],
  },
  {
    symbol: "SHIBUSD",
    name: "Shiba Inu",
    ticker: "SHIB",
    assetClass: "crypto",
    currency: "USD",
    precision: 8,
    description: "Shiba Inu, a meme token with an ecosystem built around it, priced against the US dollar.",
    drivers: ["social-media sentiment", "token burn events", "retail speculative flow"],
  },
  {
    symbol: "SUIUSD",
    name: "Sui",
    ticker: "SUI",
    assetClass: "crypto",
    currency: "USD",
    precision: 4,
    description: "Sui, the native token of a layer-1 blockchain designed for high-throughput applications, priced against the US dollar.",
    drivers: ["network throughput growth", "ecosystem funding rounds", "developer activity"],
  },
  {
    symbol: "AVAXUSD",
    name: "Avalanche",
    ticker: "AVAX",
    assetClass: "crypto",
    currency: "USD",
    precision: 3,
    description: "Avalanche's native token, priced against the US dollar.",
    drivers: ["subnet adoption", "DeFi total value locked", "institutional partnerships"],
  },
  {
    symbol: "UNIUSD",
    name: "Uniswap",
    ticker: "UNI",
    assetClass: "crypto",
    currency: "USD",
    precision: 3,
    description: "Uniswap's governance token, tied to the largest decentralised exchange by volume, priced against the US dollar.",
    drivers: ["decentralised-exchange trading volume", "fee-switch governance decisions", "DeFi risk appetite"],
  },
  {
    symbol: "NEARUSD",
    name: "NEAR Protocol",
    ticker: "NEAR",
    assetClass: "crypto",
    currency: "USD",
    precision: 3,
    description: "NEAR Protocol's native token, priced against the US dollar.",
    drivers: ["developer activity", "AI-agent narrative flows", "layer-1 competition"],
  },
  {
    symbol: "TAOUSD",
    name: "Bittensor",
    ticker: "TAO",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "Bittensor's native token, tied to a decentralised network for machine-learning models, priced against the US dollar.",
    drivers: ["AI-sector sentiment", "subnet emissions schedule", "speculative retail flow"],
  },
  {
    symbol: "AAVEUSD",
    name: "Aave",
    ticker: "AAVE",
    assetClass: "crypto",
    currency: "USD",
    precision: 2,
    description: "Aave's governance token, tied to one of the largest decentralised lending protocols, priced against the US dollar.",
    drivers: ["lending-market total value locked", "protocol fee revenue", "DeFi risk appetite"],
  },
  {
    symbol: "DOTUSD",
    name: "Polkadot",
    ticker: "DOT",
    assetClass: "crypto",
    currency: "USD",
    precision: 4,
    description: "Polkadot's native token, used to secure and coordinate its parachain network, priced against the US dollar.",
    drivers: ["parachain auction activity", "interoperability narrative", "developer activity"],
  },

  // --- Forex — expanded universe ---
  // Sourced live via Frankfurter (ECB reference rates, keyless). Every pair
  // here is between two currencies the ECB publishes daily, so cross rates
  // resolve reliably without needing Twelve Data's key or leaning on Yahoo,
  // which this codebase has already found throttles hard under a burst.
  {
    symbol: "USDCAD",
    name: "US Dollar / Canadian Dollar",
    ticker: "USD/CAD",
    assetClass: "forex",
    currency: "CAD",
    precision: 5,
    description: "The dollar against Canada's currency, closely tied to oil prices.",
    drivers: ["oil prices", "Bank of Canada policy", "US-Canada rate differentials"],
  },
  {
    symbol: "USDCHF",
    name: "US Dollar / Swiss Franc",
    ticker: "USD/CHF",
    assetClass: "forex",
    currency: "CHF",
    precision: 5,
    description: "The dollar against the franc, a classic safe-haven pair.",
    drivers: ["Swiss National Bank policy", "safe-haven flows", "US rate expectations"],
  },
  {
    symbol: "NZDUSD",
    name: "New Zealand Dollar / US Dollar",
    ticker: "NZD/USD",
    assetClass: "forex",
    currency: "USD",
    precision: 5,
    description: "The kiwi dollar against the US dollar, sensitive to global dairy and growth trends.",
    drivers: ["Reserve Bank of New Zealand policy", "dairy export prices", "risk sentiment"],
  },
  {
    symbol: "EURGBP",
    name: "Euro / British Pound",
    ticker: "EUR/GBP",
    assetClass: "forex",
    currency: "GBP",
    precision: 5,
    description: "The euro against sterling, a read on relative eurozone-UK growth.",
    drivers: ["ECB vs Bank of England policy", "eurozone-UK trade flows", "growth differentials"],
  },
  {
    symbol: "EURJPY",
    name: "Euro / Japanese Yen",
    ticker: "EUR/JPY",
    assetClass: "forex",
    currency: "JPY",
    precision: 3,
    description: "The euro against the yen, a common gauge of risk appetite funded in yen.",
    drivers: ["ECB vs Bank of Japan policy", "carry trade positioning", "risk sentiment"],
  },
  {
    symbol: "GBPJPY",
    name: "British Pound / Japanese Yen",
    ticker: "GBP/JPY",
    assetClass: "forex",
    currency: "JPY",
    precision: 3,
    description: "Sterling against the yen, historically one of the more volatile major crosses.",
    drivers: ["Bank of England vs Bank of Japan policy", "carry trade positioning", "risk sentiment"],
  },
  {
    symbol: "EURCHF",
    name: "Euro / Swiss Franc",
    ticker: "EUR/CHF",
    assetClass: "forex",
    currency: "CHF",
    precision: 5,
    description: "The euro against the franc, watched closely by the Swiss National Bank.",
    drivers: ["Swiss National Bank intervention risk", "eurozone growth data", "safe-haven flows"],
  },
  {
    symbol: "EURAUD",
    name: "Euro / Australian Dollar",
    ticker: "EUR/AUD",
    assetClass: "forex",
    currency: "AUD",
    precision: 5,
    description: "The euro against the Aussie dollar, a spread between eurozone and commodity-linked growth.",
    drivers: ["ECB vs RBA policy", "China demand data", "global growth spreads"],
  },
  {
    symbol: "EURCAD",
    name: "Euro / Canadian Dollar",
    ticker: "EUR/CAD",
    assetClass: "forex",
    currency: "CAD",
    precision: 5,
    description: "The euro against the Canadian dollar, blending eurozone policy with oil-price sensitivity.",
    drivers: ["ECB vs Bank of Canada policy", "oil prices", "growth differentials"],
  },
  {
    symbol: "EURNZD",
    name: "Euro / New Zealand Dollar",
    ticker: "EUR/NZD",
    assetClass: "forex",
    currency: "NZD",
    precision: 5,
    description: "The euro against the kiwi dollar, a eurozone-versus-commodity-bloc spread.",
    drivers: ["ECB vs RBNZ policy", "dairy export prices", "risk sentiment"],
  },
  {
    symbol: "GBPAUD",
    name: "British Pound / Australian Dollar",
    ticker: "GBP/AUD",
    assetClass: "forex",
    currency: "AUD",
    precision: 5,
    description: "Sterling against the Aussie dollar, a UK-versus-commodity-bloc spread.",
    drivers: ["Bank of England vs RBA policy", "commodity prices", "risk sentiment"],
  },
  {
    symbol: "GBPCAD",
    name: "British Pound / Canadian Dollar",
    ticker: "GBP/CAD",
    assetClass: "forex",
    currency: "CAD",
    precision: 5,
    description: "Sterling against the Canadian dollar.",
    drivers: ["Bank of England vs Bank of Canada policy", "oil prices", "risk sentiment"],
  },
  {
    symbol: "GBPCHF",
    name: "British Pound / Swiss Franc",
    ticker: "GBP/CHF",
    assetClass: "forex",
    currency: "CHF",
    precision: 5,
    description: "Sterling against the franc.",
    drivers: ["Bank of England policy", "safe-haven flows", "UK political risk"],
  },
  {
    symbol: "GBPNZD",
    name: "British Pound / New Zealand Dollar",
    ticker: "GBP/NZD",
    assetClass: "forex",
    currency: "NZD",
    precision: 5,
    description: "Sterling against the kiwi dollar.",
    drivers: ["Bank of England vs RBNZ policy", "dairy export prices", "risk sentiment"],
  },
  {
    symbol: "AUDJPY",
    name: "Australian Dollar / Japanese Yen",
    ticker: "AUD/JPY",
    assetClass: "forex",
    currency: "JPY",
    precision: 3,
    description: "The Aussie dollar against the yen, a widely-watched risk-appetite barometer.",
    drivers: ["carry trade positioning", "China demand data", "risk sentiment"],
  },
  {
    symbol: "AUDCAD",
    name: "Australian Dollar / Canadian Dollar",
    ticker: "AUD/CAD",
    assetClass: "forex",
    currency: "CAD",
    precision: 5,
    description: "A spread between two commodity-linked currencies.",
    drivers: ["iron ore vs oil prices", "RBA vs Bank of Canada policy", "China demand data"],
  },
  {
    symbol: "AUDCHF",
    name: "Australian Dollar / Swiss Franc",
    ticker: "AUD/CHF",
    assetClass: "forex",
    currency: "CHF",
    precision: 5,
    description: "The Aussie dollar against the franc, commodity growth versus safe-haven demand.",
    drivers: ["risk sentiment", "safe-haven flows", "RBA policy"],
  },
  {
    symbol: "AUDNZD",
    name: "Australian Dollar / New Zealand Dollar",
    ticker: "AUD/NZD",
    assetClass: "forex",
    currency: "NZD",
    precision: 5,
    description: "The trans-Tasman cross between Australia's and New Zealand's dollars.",
    drivers: ["RBA vs RBNZ policy", "relative commodity export prices", "growth differentials"],
  },
  {
    symbol: "CADJPY",
    name: "Canadian Dollar / Japanese Yen",
    ticker: "CAD/JPY",
    assetClass: "forex",
    currency: "JPY",
    precision: 3,
    description: "The Canadian dollar against the yen, tying oil prices to carry-trade flows.",
    drivers: ["oil prices", "carry trade positioning", "risk sentiment"],
  },
  {
    symbol: "CHFJPY",
    name: "Swiss Franc / Japanese Yen",
    ticker: "CHF/JPY",
    assetClass: "forex",
    currency: "JPY",
    precision: 3,
    description: "A cross between two traditional safe-haven currencies.",
    drivers: ["Swiss National Bank policy", "Bank of Japan policy", "safe-haven flows"],
  },
  {
    symbol: "NZDJPY",
    name: "New Zealand Dollar / Japanese Yen",
    ticker: "NZD/JPY",
    assetClass: "forex",
    currency: "JPY",
    precision: 3,
    description: "The kiwi dollar against the yen, a smaller-scale carry-trade pair.",
    drivers: ["carry trade positioning", "dairy export prices", "risk sentiment"],
  },
  {
    symbol: "USDSEK",
    name: "US Dollar / Swedish Krona",
    ticker: "USD/SEK",
    assetClass: "forex",
    currency: "SEK",
    precision: 4,
    description: "The dollar against Sweden's currency.",
    drivers: ["Riksbank policy", "eurozone growth spillover", "risk sentiment"],
  },
  {
    symbol: "USDNOK",
    name: "US Dollar / Norwegian Krone",
    ticker: "USD/NOK",
    assetClass: "forex",
    currency: "NOK",
    precision: 4,
    description: "The dollar against Norway's currency, closely tied to oil exports.",
    drivers: ["oil prices", "Norges Bank policy", "risk sentiment"],
  },
  {
    symbol: "USDZAR",
    name: "US Dollar / South African Rand",
    ticker: "USD/ZAR",
    assetClass: "forex",
    currency: "ZAR",
    precision: 4,
    description: "The dollar against the rand, sensitive to commodity prices and emerging-market risk appetite.",
    drivers: ["gold and platinum prices", "South African Reserve Bank policy", "emerging-market risk appetite"],
  },
  {
    symbol: "USDMXN",
    name: "US Dollar / Mexican Peso",
    ticker: "USD/MXN",
    assetClass: "forex",
    currency: "MXN",
    precision: 4,
    description: "The dollar against the peso, closely tied to US-Mexico trade and rate differentials.",
    drivers: ["Banco de México policy", "US-Mexico trade flows", "emerging-market risk appetite"],
  },
  {
    symbol: "USDSGD",
    name: "US Dollar / Singapore Dollar",
    ticker: "USD/SGD",
    assetClass: "forex",
    currency: "SGD",
    precision: 5,
    description: "The dollar against the Singapore dollar, managed within a policy band rather than freely floated.",
    drivers: ["Monetary Authority of Singapore policy band", "regional trade flows", "risk sentiment"],
  },
  {
    symbol: "USDHKD",
    name: "US Dollar / Hong Kong Dollar",
    ticker: "USD/HKD",
    assetClass: "forex",
    currency: "HKD",
    precision: 4,
    description: "The dollar against the Hong Kong dollar, pegged within a narrow band by the currency board.",
    drivers: ["Hong Kong currency board interventions", "US rate policy", "capital flows"],
  },
  {
    symbol: "USDCNY",
    name: "US Dollar / Chinese Yuan",
    ticker: "USD/CNY",
    assetClass: "forex",
    currency: "CNY",
    precision: 4,
    description: "The dollar against China's currency, managed within a daily reference band.",
    drivers: ["PBoC daily fixing", "China trade data", "capital flow controls"],
  },
];

/** The nine markets shown on the Markets grid and the landing ticker. */
export const FEATURED_SYMBOLS = [
  "XAUUSD",
  "BTCUSD",
  "ETHUSD",
  "EURUSD",
  "GBPUSD",
  "USDJPY",
  "NDX",
  "SPX",
  "WTIUSD",
] as const;

const BY_SYMBOL = new Map(ASSETS.map((a) => [a.symbol, a]));

export function getAsset(symbol: string): Asset | undefined {
  return BY_SYMBOL.get(symbol.toUpperCase());
}

/** Throws for unknown symbols — use in routes that already validated input. */
export function requireAsset(symbol: string): Asset {
  const asset = getAsset(symbol);
  if (!asset) throw new Error(`Unknown symbol: ${symbol}`);
  return asset;
}

export function getFeaturedAssets(): Asset[] {
  return FEATURED_SYMBOLS.map((s) => requireAsset(s));
}

export const ASSET_CLASS_LABEL: Record<AssetClass, string> = {
  commodity: "Commodities",
  crypto: "Crypto",
  forex: "Forex",
  index: "Indices",
  stock: "Stocks",
  energy: "Energy",
};

/** Simple fuzzy-ish search across symbol, name and ticker. */
export function searchAssets(query: string, limit = 8): Asset[] {
  const q = query.trim().toLowerCase();
  if (!q) return getFeaturedAssets().slice(0, limit);

  return ASSETS.map((asset) => {
    const symbol = asset.symbol.toLowerCase();
    const name = asset.name.toLowerCase();
    const ticker = asset.ticker.toLowerCase();

    let score = 0;
    if (symbol === q || ticker === q) score = 100;
    else if (symbol.startsWith(q) || ticker.startsWith(q)) score = 80;
    else if (name.toLowerCase().startsWith(q)) score = 70;
    else if (name.includes(q)) score = 50;
    else if (symbol.includes(q) || ticker.includes(q)) score = 40;

    return { asset, score };
  })
    .filter((r) => r.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((r) => r.asset);
}
