import { analyseAsset } from "@/lib/ai/analysis";
import { getAsset } from "@/lib/market/catalog";
import { loadMacroEvents } from "./agents/macro";
import { loadRelevantNews } from "./agents/news";
import { buildSuggestion } from "./agents/technical";
import type { TradeAnalysis } from "./types";

const WHALE_ACTIVITY_NOTE =
  "Not available — order-flow data requires a live exchange connection, planned for a later phase.";
const FUNDING_RATE_NOTE =
  "Not available — funding rate is exchange-specific and requires a live Bybit connection, planned for a later phase.";

/**
 * Composes the AI Analysis panel's output for one symbol.
 *
 * Every field traces back to the deterministic analysis engine or the news
 * provider. Nothing here is generated by a language model, and nothing is
 * invented to fill a field this app has no real data source for — Whale
 * Activity and Funding Rate say so plainly instead.
 */
export async function composeTradeAnalysis(symbol: string): Promise<TradeAnalysis | null> {
  const asset = getAsset(symbol);
  if (!asset) return null;

  const [analysis, news] = await Promise.all([
    analyseAsset(symbol, "3M"),
    loadRelevantNews(symbol, 3),
  ]);

  const momentum = analysis.indicators.find((indicator) => indicator.key === "macd");
  const volume = analysis.indicators.find((indicator) => indicator.key === "volume");

  return {
    symbol: asset.symbol,
    assetName: asset.name,
    precision: asset.precision,
    generatedAt: analysis.generatedAt,
    price: analysis.price,
    changePercent: analysis.changePercent,
    trend: analysis.trend.direction,
    confidenceScore: analysis.trend.confidence,
    momentum: momentum
      ? { value: momentum.value, interpretation: momentum.interpretation }
      : { value: "n/a", interpretation: "Not enough history to read momentum yet." },
    support: analysis.supports,
    resistance: analysis.resistances,
    risk: {
      regime: analysis.volatility.regime,
      description: analysis.volatility.description,
    },
    volumeAnalysis: volume
      ? { value: volume.value, interpretation: volume.interpretation }
      : { value: "n/a", interpretation: "Volume is not published for this market." },
    reasons: analysis.trend.contributions.map(
      (contribution) => `${contribution.label} reads ${contribution.signal}`,
    ),
    newsSummary: news.map((article) => ({
      headline: article.headline,
      summary: article.summary,
      impact: article.impact.direction,
    })),
    macroEvents: loadMacroEvents(analysis),
    whaleActivityNote: WHALE_ACTIVITY_NOTE,
    fundingRateNote: FUNDING_RATE_NOTE,
    suggestion: buildSuggestion(analysis),
    narrator: "rules",
  };
}
